# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
 
- script: |
    npm i -D jest-junit-reporter
  displayName: 'install jest-junit-reporter'

- script: |
    mkdir $(TEST_REPORT_PATH)
    npm run test
    ls $(TEST_REPORT_PATH)
  displayName: 'npm test -- --coverage'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(TEST_REPORT_PATH)/test-report.xml'

- script: |
    npm run build
  displayName: 'npm build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build'
    ArtifactName: 'drop'
    publishLocation: 'Container'

