name: deploy app

# on:
#   release:
#     types: [created]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: samplecrm-myrapp
  AZURE_WEBAPP_PACKAGE_PATH: './build'
  NODE_VERSION: '10.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test

    - name: 'Deploy to Azure'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-test:
    name: Test Deployment
    runs-on: ubuntu-latest
    environment: test
    needs: build-and-deploy
    
    steps:
    - name: Deploy Test
      run: echo 'github event name ${{ github.event_name }}'


