name: deploy app

on:
  push:
    branches: [ master ]

env:
  AZURE_WEBAPP_PACKAGE_PATH: './build'
  NODE_VERSION: '10.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    environment: Dev
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
    - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-dev:
    name: Dev Deployment
    environment: Dev
    runs-on: ubuntu-latest
    needs: build
    env:
      AZURE_WEBAPP_NAME: samplecrm-myrapp
    
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: build

    - name: 'Deploy to Azure'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-test:
    name: Test Deployment
    runs-on: ubuntu-latest
    environment: Test
    needs: deploy-dev
    env:
      AZURE_WEBAPP_NAME: samplecrm-myrapp-test
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test

    - name: 'Deploy to Azure'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}


